/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from "@tanstack/react-router"

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as LayoutImport } from "./routes/_layout"
import { Route as LayoutIndexImport } from "./routes/_layout/index"
import { Route as AuthAuthLayoutImport } from "./routes/auth/_auth-layout"
import { Route as AuthAuthLayoutIndexImport } from "./routes/auth/_auth-layout/index"
import { Route as LayoutUsersIndexImport } from "./routes/_layout/users/index"
import { Route as LayoutUsersResultsIndexImport } from "./routes/_layout/users-results/index"
import { Route as LayoutTestsIndexImport } from "./routes/_layout/tests/index"
import { Route as LayoutSubjectsIndexImport } from "./routes/_layout/subjects/index"
import { Route as LayoutStatisticsIndexImport } from "./routes/_layout/statistics/index"
import { Route as LayoutProfileIndexImport } from "./routes/_layout/profile/index"
import { Route as LayoutExamsIndexImport } from "./routes/_layout/exams/index"
import { Route as AuthAuthLayoutRegisterImport } from "./routes/auth/_auth-layout/register"
import { Route as AuthAuthLayoutLoginImport } from "./routes/auth/_auth-layout/login"
import { Route as LayoutUsersUserIdImport } from "./routes/_layout/users/$userId"
import { Route as LayoutSubjectsSubjectIdImport } from "./routes/_layout/subjects/$subjectId"
import { Route as LayoutExamsExamIdImport } from "./routes/_layout/exams/$examId"
import { Route as LayoutTestsTestIdIndexImport } from "./routes/_layout/tests/$testId/index"

// Create Virtual Routes

const AuthImport = createFileRoute("/auth")()

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: "/auth",
  path: "/auth",
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: "/_layout",
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => LayoutRoute,
} as any)

const AuthAuthLayoutRoute = AuthAuthLayoutImport.update({
  id: "/_auth-layout",
  getParentRoute: () => AuthRoute,
} as any)

const AuthAuthLayoutIndexRoute = AuthAuthLayoutIndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthAuthLayoutRoute,
} as any)

const LayoutUsersIndexRoute = LayoutUsersIndexImport.update({
  id: "/users/",
  path: "/users/",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutUsersResultsIndexRoute = LayoutUsersResultsIndexImport.update({
  id: "/users-results/",
  path: "/users-results/",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTestsIndexRoute = LayoutTestsIndexImport.update({
  id: "/tests/",
  path: "/tests/",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSubjectsIndexRoute = LayoutSubjectsIndexImport.update({
  id: "/subjects/",
  path: "/subjects/",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutStatisticsIndexRoute = LayoutStatisticsIndexImport.update({
  id: "/statistics/",
  path: "/statistics/",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutProfileIndexRoute = LayoutProfileIndexImport.update({
  id: "/profile/",
  path: "/profile/",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutExamsIndexRoute = LayoutExamsIndexImport.update({
  id: "/exams/",
  path: "/exams/",
  getParentRoute: () => LayoutRoute,
} as any)

const AuthAuthLayoutRegisterRoute = AuthAuthLayoutRegisterImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => AuthAuthLayoutRoute,
} as any)

const AuthAuthLayoutLoginRoute = AuthAuthLayoutLoginImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthAuthLayoutRoute,
} as any)

const LayoutUsersUserIdRoute = LayoutUsersUserIdImport.update({
  id: "/users/$userId",
  path: "/users/$userId",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSubjectsSubjectIdRoute = LayoutSubjectsSubjectIdImport.update({
  id: "/subjects/$subjectId",
  path: "/subjects/$subjectId",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutExamsExamIdRoute = LayoutExamsExamIdImport.update({
  id: "/exams/$examId",
  path: "/exams/$examId",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTestsTestIdIndexRoute = LayoutTestsTestIdIndexImport.update({
  id: "/tests/$testId/",
  path: "/tests/$testId/",
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_layout": {
      id: "/_layout"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    "/auth": {
      id: "/auth"
      path: "/auth"
      fullPath: "/auth"
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    "/auth/_auth-layout": {
      id: "/auth/_auth-layout"
      path: "/auth"
      fullPath: "/auth"
      preLoaderRoute: typeof AuthAuthLayoutImport
      parentRoute: typeof AuthRoute
    }
    "/_layout/": {
      id: "/_layout/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/exams/$examId": {
      id: "/_layout/exams/$examId"
      path: "/exams/$examId"
      fullPath: "/exams/$examId"
      preLoaderRoute: typeof LayoutExamsExamIdImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/subjects/$subjectId": {
      id: "/_layout/subjects/$subjectId"
      path: "/subjects/$subjectId"
      fullPath: "/subjects/$subjectId"
      preLoaderRoute: typeof LayoutSubjectsSubjectIdImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/users/$userId": {
      id: "/_layout/users/$userId"
      path: "/users/$userId"
      fullPath: "/users/$userId"
      preLoaderRoute: typeof LayoutUsersUserIdImport
      parentRoute: typeof LayoutImport
    }
    "/auth/_auth-layout/login": {
      id: "/auth/_auth-layout/login"
      path: "/login"
      fullPath: "/auth/login"
      preLoaderRoute: typeof AuthAuthLayoutLoginImport
      parentRoute: typeof AuthAuthLayoutImport
    }
    "/auth/_auth-layout/register": {
      id: "/auth/_auth-layout/register"
      path: "/register"
      fullPath: "/auth/register"
      preLoaderRoute: typeof AuthAuthLayoutRegisterImport
      parentRoute: typeof AuthAuthLayoutImport
    }
    "/_layout/exams/": {
      id: "/_layout/exams/"
      path: "/exams"
      fullPath: "/exams"
      preLoaderRoute: typeof LayoutExamsIndexImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/profile/": {
      id: "/_layout/profile/"
      path: "/profile"
      fullPath: "/profile"
      preLoaderRoute: typeof LayoutProfileIndexImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/statistics/": {
      id: "/_layout/statistics/"
      path: "/statistics"
      fullPath: "/statistics"
      preLoaderRoute: typeof LayoutStatisticsIndexImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/subjects/": {
      id: "/_layout/subjects/"
      path: "/subjects"
      fullPath: "/subjects"
      preLoaderRoute: typeof LayoutSubjectsIndexImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/tests/": {
      id: "/_layout/tests/"
      path: "/tests"
      fullPath: "/tests"
      preLoaderRoute: typeof LayoutTestsIndexImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/users-results/": {
      id: "/_layout/users-results/"
      path: "/users-results"
      fullPath: "/users-results"
      preLoaderRoute: typeof LayoutUsersResultsIndexImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/users/": {
      id: "/_layout/users/"
      path: "/users"
      fullPath: "/users"
      preLoaderRoute: typeof LayoutUsersIndexImport
      parentRoute: typeof LayoutImport
    }
    "/auth/_auth-layout/": {
      id: "/auth/_auth-layout/"
      path: "/"
      fullPath: "/auth/"
      preLoaderRoute: typeof AuthAuthLayoutIndexImport
      parentRoute: typeof AuthAuthLayoutImport
    }
    "/_layout/tests/$testId/": {
      id: "/_layout/tests/$testId/"
      path: "/tests/$testId"
      fullPath: "/tests/$testId"
      preLoaderRoute: typeof LayoutTestsTestIdIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutExamsExamIdRoute: typeof LayoutExamsExamIdRoute
  LayoutSubjectsSubjectIdRoute: typeof LayoutSubjectsSubjectIdRoute
  LayoutUsersUserIdRoute: typeof LayoutUsersUserIdRoute
  LayoutExamsIndexRoute: typeof LayoutExamsIndexRoute
  LayoutProfileIndexRoute: typeof LayoutProfileIndexRoute
  LayoutStatisticsIndexRoute: typeof LayoutStatisticsIndexRoute
  LayoutSubjectsIndexRoute: typeof LayoutSubjectsIndexRoute
  LayoutTestsIndexRoute: typeof LayoutTestsIndexRoute
  LayoutUsersResultsIndexRoute: typeof LayoutUsersResultsIndexRoute
  LayoutUsersIndexRoute: typeof LayoutUsersIndexRoute
  LayoutTestsTestIdIndexRoute: typeof LayoutTestsTestIdIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutExamsExamIdRoute: LayoutExamsExamIdRoute,
  LayoutSubjectsSubjectIdRoute: LayoutSubjectsSubjectIdRoute,
  LayoutUsersUserIdRoute: LayoutUsersUserIdRoute,
  LayoutExamsIndexRoute: LayoutExamsIndexRoute,
  LayoutProfileIndexRoute: LayoutProfileIndexRoute,
  LayoutStatisticsIndexRoute: LayoutStatisticsIndexRoute,
  LayoutSubjectsIndexRoute: LayoutSubjectsIndexRoute,
  LayoutTestsIndexRoute: LayoutTestsIndexRoute,
  LayoutUsersResultsIndexRoute: LayoutUsersResultsIndexRoute,
  LayoutUsersIndexRoute: LayoutUsersIndexRoute,
  LayoutTestsTestIdIndexRoute: LayoutTestsTestIdIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface AuthAuthLayoutRouteChildren {
  AuthAuthLayoutLoginRoute: typeof AuthAuthLayoutLoginRoute
  AuthAuthLayoutRegisterRoute: typeof AuthAuthLayoutRegisterRoute
  AuthAuthLayoutIndexRoute: typeof AuthAuthLayoutIndexRoute
}

const AuthAuthLayoutRouteChildren: AuthAuthLayoutRouteChildren = {
  AuthAuthLayoutLoginRoute: AuthAuthLayoutLoginRoute,
  AuthAuthLayoutRegisterRoute: AuthAuthLayoutRegisterRoute,
  AuthAuthLayoutIndexRoute: AuthAuthLayoutIndexRoute,
}

const AuthAuthLayoutRouteWithChildren = AuthAuthLayoutRoute._addFileChildren(
  AuthAuthLayoutRouteChildren,
)

interface AuthRouteChildren {
  AuthAuthLayoutRoute: typeof AuthAuthLayoutRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthLayoutRoute: AuthAuthLayoutRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  "": typeof LayoutRouteWithChildren
  "/auth": typeof AuthAuthLayoutRouteWithChildren
  "/": typeof LayoutIndexRoute
  "/exams/$examId": typeof LayoutExamsExamIdRoute
  "/subjects/$subjectId": typeof LayoutSubjectsSubjectIdRoute
  "/users/$userId": typeof LayoutUsersUserIdRoute
  "/auth/login": typeof AuthAuthLayoutLoginRoute
  "/auth/register": typeof AuthAuthLayoutRegisterRoute
  "/exams": typeof LayoutExamsIndexRoute
  "/profile": typeof LayoutProfileIndexRoute
  "/statistics": typeof LayoutStatisticsIndexRoute
  "/subjects": typeof LayoutSubjectsIndexRoute
  "/tests": typeof LayoutTestsIndexRoute
  "/users-results": typeof LayoutUsersResultsIndexRoute
  "/users": typeof LayoutUsersIndexRoute
  "/auth/": typeof AuthAuthLayoutIndexRoute
  "/tests/$testId": typeof LayoutTestsTestIdIndexRoute
}

export interface FileRoutesByTo {
  "/auth": typeof AuthAuthLayoutIndexRoute
  "/": typeof LayoutIndexRoute
  "/exams/$examId": typeof LayoutExamsExamIdRoute
  "/subjects/$subjectId": typeof LayoutSubjectsSubjectIdRoute
  "/users/$userId": typeof LayoutUsersUserIdRoute
  "/auth/login": typeof AuthAuthLayoutLoginRoute
  "/auth/register": typeof AuthAuthLayoutRegisterRoute
  "/exams": typeof LayoutExamsIndexRoute
  "/profile": typeof LayoutProfileIndexRoute
  "/statistics": typeof LayoutStatisticsIndexRoute
  "/subjects": typeof LayoutSubjectsIndexRoute
  "/tests": typeof LayoutTestsIndexRoute
  "/users-results": typeof LayoutUsersResultsIndexRoute
  "/users": typeof LayoutUsersIndexRoute
  "/tests/$testId": typeof LayoutTestsTestIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  "/_layout": typeof LayoutRouteWithChildren
  "/auth": typeof AuthRouteWithChildren
  "/auth/_auth-layout": typeof AuthAuthLayoutRouteWithChildren
  "/_layout/": typeof LayoutIndexRoute
  "/_layout/exams/$examId": typeof LayoutExamsExamIdRoute
  "/_layout/subjects/$subjectId": typeof LayoutSubjectsSubjectIdRoute
  "/_layout/users/$userId": typeof LayoutUsersUserIdRoute
  "/auth/_auth-layout/login": typeof AuthAuthLayoutLoginRoute
  "/auth/_auth-layout/register": typeof AuthAuthLayoutRegisterRoute
  "/_layout/exams/": typeof LayoutExamsIndexRoute
  "/_layout/profile/": typeof LayoutProfileIndexRoute
  "/_layout/statistics/": typeof LayoutStatisticsIndexRoute
  "/_layout/subjects/": typeof LayoutSubjectsIndexRoute
  "/_layout/tests/": typeof LayoutTestsIndexRoute
  "/_layout/users-results/": typeof LayoutUsersResultsIndexRoute
  "/_layout/users/": typeof LayoutUsersIndexRoute
  "/auth/_auth-layout/": typeof AuthAuthLayoutIndexRoute
  "/_layout/tests/$testId/": typeof LayoutTestsTestIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ""
    | "/auth"
    | "/"
    | "/exams/$examId"
    | "/subjects/$subjectId"
    | "/users/$userId"
    | "/auth/login"
    | "/auth/register"
    | "/exams"
    | "/profile"
    | "/statistics"
    | "/subjects"
    | "/tests"
    | "/users-results"
    | "/users"
    | "/auth/"
    | "/tests/$testId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/auth"
    | "/"
    | "/exams/$examId"
    | "/subjects/$subjectId"
    | "/users/$userId"
    | "/auth/login"
    | "/auth/register"
    | "/exams"
    | "/profile"
    | "/statistics"
    | "/subjects"
    | "/tests"
    | "/users-results"
    | "/users"
    | "/tests/$testId"
  id:
    | "__root__"
    | "/_layout"
    | "/auth"
    | "/auth/_auth-layout"
    | "/_layout/"
    | "/_layout/exams/$examId"
    | "/_layout/subjects/$subjectId"
    | "/_layout/users/$userId"
    | "/auth/_auth-layout/login"
    | "/auth/_auth-layout/register"
    | "/_layout/exams/"
    | "/_layout/profile/"
    | "/_layout/statistics/"
    | "/_layout/subjects/"
    | "/_layout/tests/"
    | "/_layout/users-results/"
    | "/_layout/users/"
    | "/auth/_auth-layout/"
    | "/_layout/tests/$testId/"
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/auth"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/",
        "/_layout/exams/$examId",
        "/_layout/subjects/$subjectId",
        "/_layout/users/$userId",
        "/_layout/exams/",
        "/_layout/profile/",
        "/_layout/statistics/",
        "/_layout/subjects/",
        "/_layout/tests/",
        "/_layout/users-results/",
        "/_layout/users/",
        "/_layout/tests/$testId/"
      ]
    },
    "/auth": {
      "filePath": "auth",
      "children": [
        "/auth/_auth-layout"
      ]
    },
    "/auth/_auth-layout": {
      "filePath": "auth/_auth-layout.tsx",
      "parent": "/auth",
      "children": [
        "/auth/_auth-layout/login",
        "/auth/_auth-layout/register",
        "/auth/_auth-layout/"
      ]
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/exams/$examId": {
      "filePath": "_layout/exams/$examId.tsx",
      "parent": "/_layout"
    },
    "/_layout/subjects/$subjectId": {
      "filePath": "_layout/subjects/$subjectId.tsx",
      "parent": "/_layout"
    },
    "/_layout/users/$userId": {
      "filePath": "_layout/users/$userId.tsx",
      "parent": "/_layout"
    },
    "/auth/_auth-layout/login": {
      "filePath": "auth/_auth-layout/login.tsx",
      "parent": "/auth/_auth-layout"
    },
    "/auth/_auth-layout/register": {
      "filePath": "auth/_auth-layout/register.tsx",
      "parent": "/auth/_auth-layout"
    },
    "/_layout/exams/": {
      "filePath": "_layout/exams/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/profile/": {
      "filePath": "_layout/profile/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/statistics/": {
      "filePath": "_layout/statistics/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/subjects/": {
      "filePath": "_layout/subjects/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/tests/": {
      "filePath": "_layout/tests/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/users-results/": {
      "filePath": "_layout/users-results/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/users/": {
      "filePath": "_layout/users/index.tsx",
      "parent": "/_layout"
    },
    "/auth/_auth-layout/": {
      "filePath": "auth/_auth-layout/index.tsx",
      "parent": "/auth/_auth-layout"
    },
    "/_layout/tests/$testId/": {
      "filePath": "_layout/tests/$testId/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
